---
sudo: false
language: ruby
cache: bundler
script: "bundle exec rake validate lint spec"
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 4.0"
notifications:
  email: false