source 'https://rubygems.org'

gem 'test-kitchen'
gem 'serverspec'
gem 'busser-serverspec'
gem 'busser'
gem 'psych'
gem 'kitchen-vagrant'
gem 'kitchen-puppet'
gem 'puppet'
gem 'librarian-puppet'
gem 'puppet-lint'
